'''
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
        Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
        Pentagonal      Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
        Hexagonal       Hn=n(2n-1)      1, 6, 15, 28, 45, ...
    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.
'''
from __future__ import division
from math import sqrt

def genTriangular():
    '''Generate an infinite list of triangular numbers'''
    triangleSum = 1
    counter = 1
    while True:
        yield triangleSum
        counter += 1
        triangleSum += counter
    
def isPentagonal(P):
    checkNum = (1 + sqrt(1 + 24*P))/6
    return int(checkNum) == checkNum

def isHexagonal(H):
    checkNum = (1 + sqrt(1+8*H))/4
    return int(checkNum)  == checkNum
    
for triNum in genTriangular():
    if isPentagonal(triNum) and isHexagonal(triNum):
        print triNum
        